### ISSUE TITLE
enhancements to tmp2ind_T1T2.sh (and tmp2ind_T1.sh)

### ISSUE THREAD

**Issue by jcrdubois** [jmtyszka/atlaskit#1]
A few suggestions:
- add an input argument for nthreads
- if probability atlas is 4d, then WarpImageMultiTransform is not appropriate; you need to use WarpTimeSeriesImageMultiTransform (currently only the first volume of the probability atlas gets transformed)
- make input probability atlas optional; it can be transformed at a later step using the learned affine & warp

Happy to make & push these edits if you agree.

**Comment by wmpauli** [comment]
Thank you for these suggestions!

**Comment by jmtyszka** [comment]
Hi Julien,

Yes, all excellent suggestions! If you have the time to implement these, I’ll accept the pull request on arrival. Let me know.

Cheers,

Mike

J. Michael Tyszka, Ph.D. | Associate Director | Caltech Brain Imaging Center
Caltech | Broad 114-96 | Pasadena CA 91125 | (626) 395-5796 | http://www.its.caltech.edu/~jmt

**Comment by jcrdubois** [comment]
ok, I made changes (also named arguments), testing them before pushing

**Comment by jcrdubois** [comment]
I pushed my enhancements, for tmp2ind_T1T2.sh
Let me know if it works for you. We should enhance tmp2ind_T1.sh similarly for consistency.

**Comment by jmtyszka** [comment]
Thanks Julien! These changes look great and I'm in the process of porting them to the T1 script now.
